<?php
namespace Gitcd\Plugins\sulla;

use Gitcd\Helpers\Shell;

class SullaHelper
{
    const GITHUB_REPO  = 'merchantprotocol/sulla-agent';
    const GITHUB_SSH   = 'git@github.com:merchantprotocol/sulla-agent.git';
    const BINARY_NAME  = 'sulla-agent';

    /**
     * Root directory where the sulla agent is installed.
     */
    public static function installDir(): string
    {
        $home = getenv('HOME') ?: getenv('USERPROFILE') ?: '/tmp';
        $dir = $home . DIRECTORY_SEPARATOR . '.protocol' . DIRECTORY_SEPARATOR . 'sulla' . DIRECTORY_SEPARATOR;
        if (!is_dir($dir)) {
            mkdir($dir, 0700, true);
        }
        return $dir;
    }

    /**
     * The cloned repo directory inside the install dir.
     */
    public static function repoDir(): string
    {
        return self::installDir() . 'sulla-agent' . DIRECTORY_SEPARATOR;
    }

    /**
     * Full path to the built JS entry point.
     */
    public static function entryScript(): string
    {
        return self::repoDir() . 'dist' . DIRECTORY_SEPARATOR . 'sulla-agent.js';
    }

    /**
     * Full path to the wrapper shell script that acts as the "binary".
     */
    public static function binaryPath(): string
    {
        return self::installDir() . self::BINARY_NAME;
    }

    /**
     * Full path to the .env configuration file.
     */
    public static function envPath(): string
    {
        return self::installDir() . '.env';
    }

    /**
     * Check if the sulla-agent is installed (repo cloned, built, wrapper exists).
     */
    public static function isInstalled(): bool
    {
        return is_file(self::entryScript()) && is_file(self::binaryPath());
    }

    /**
     * Check if the sulla-agent process is currently running.
     */
    public static function isRunning(): bool
    {
        $pidFile = self::installDir() . 'sulla-agent.pid';
        if (!is_file($pidFile)) {
            return false;
        }
        $pid = trim(file_get_contents($pidFile));
        return $pid && Shell::isRunning((int) $pid);
    }

    /**
     * Get the PID of the running sulla-agent, or null.
     */
    public static function getPid(): ?int
    {
        $pidFile = self::installDir() . 'sulla-agent.pid';
        if (!is_file($pidFile)) {
            return null;
        }
        $pid = (int) trim(file_get_contents($pidFile));
        return $pid > 0 ? $pid : null;
    }

    /**
     * Create a wrapper shell script that loads .env and runs the agent.
     */
    public static function createWrapper(): void
    {
        $wrapperPath = self::binaryPath();
        $entryScript = self::entryScript();
        $envFile = self::envPath();

        $wrapper = <<<BASH
#!/usr/bin/env bash
# Sulla agent wrapper — generated by protocol sulla:install
set -euo pipefail

# Load .env if present
ENV_FILE="{$envFile}"
if [ -f "\$ENV_FILE" ]; then
    set -a
    source "\$ENV_FILE"
    set +a
fi

exec node "{$entryScript}" "\$@"
BASH;

        file_put_contents($wrapperPath, $wrapper . "\n", LOCK_EX);
        chmod($wrapperPath, 0755);
    }

    /**
     * Read a value from the .env file.
     */
    public static function readEnv(string $key): string
    {
        $envFile = self::envPath();
        if (!is_file($envFile)) {
            return '';
        }
        foreach (file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
            if (str_starts_with($line, '#')) continue;
            $parts = explode('=', $line, 2);
            if (count($parts) === 2 && trim($parts[0]) === $key) {
                return trim($parts[1]);
            }
        }
        return '';
    }

    /**
     * Write or update a value in the .env file.
     */
    public static function writeEnv(string $key, string $value): void
    {
        $envFile = self::envPath();
        $lines = [];
        $found = false;

        if (is_file($envFile)) {
            foreach (file($envFile, FILE_IGNORE_NEW_LINES) as $line) {
                $parts = explode('=', $line, 2);
                if (count($parts) === 2 && trim($parts[0]) === $key) {
                    $lines[] = "{$key}={$value}";
                    $found = true;
                } else {
                    $lines[] = $line;
                }
            }
        }

        if (!$found) {
            $lines[] = "{$key}={$value}";
        }

        file_put_contents($envFile, implode("\n", $lines) . "\n", LOCK_EX);
    }
}
